M48
; DRILL file {KiCad 8.0.1} date 2024-04-28T18:54:04+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-28T18:54:04+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X123.594Y-91.437
X145.844Y-113.078
X167.993Y-91.437
M30
